#!/bin/bash
set -euo pipefail

# Only run in Claude Code on the web remote environment
if [ "${CLAUDE_CODE_REMOTE:-}" != "true" ]; then
  exit 0
fi

echo "Setting up Ruby environment for Lich 5..."

# Get Ruby version and gem path
RUBY_VERSION=$(ruby -e 'puts RUBY_VERSION')
GEM_HOME=$(ruby -e 'puts Gem.dir')
GEM_BIN_DIR="${GEM_HOME}/bin"

echo "Ruby version: ${RUBY_VERSION}"
echo "Gem home: ${GEM_HOME}"
echo "Gem bin directory: ${GEM_BIN_DIR}"

# Create gem bin directory if it doesn't exist
# This is critical - bundler expects this directory to exist for gem executables
if [ ! -d "${GEM_BIN_DIR}" ]; then
  echo "Creating missing gem bin directory: ${GEM_BIN_DIR}"
  mkdir -p "${GEM_BIN_DIR}"
fi

# Install bundler dependencies
echo "Installing bundle dependencies..."
bundle install --quiet

# Create wrapper scripts for rspec and rubocop
# These executables need to be in the gem bin directory for 'bundle exec' to find them
echo "Creating gem executable wrappers..."

cat > "${GEM_BIN_DIR}/rspec" << 'RSPEC_EOF'
#!/usr/bin/env ruby
# This file was generated by RubyGems.
require 'rubygems'

version = ">= 0.a"

str = ARGV.first
if str
  str = str.b[/\A_(.*)_\z/, 1]
  if str and Gem::Version.correct?(str)
    version = str
    ARGV.shift
  end
end

if Gem.respond_to?(:activate_bin_path)
load Gem.activate_bin_path('rspec-core', 'rspec', version)
else
gem "rspec-core", version
load Gem.bin_path("rspec-core", "rspec", version)
end
RSPEC_EOF

cat > "${GEM_BIN_DIR}/rubocop" << 'RUBOCOP_EOF'
#!/usr/bin/env ruby
# This file was generated by RubyGems.
require 'rubygems'

version = ">= 0.a"

str = ARGV.first
if str
  str = str.b[/\A_(.*)_\z/, 1]
  if str and Gem::Version.correct?(str)
    version = str
    ARGV.shift
  end
end

if Gem.respond_to?(:activate_bin_path)
load Gem.activate_bin_path('rubocop', 'rubocop', version)
else
gem "rubocop", version
load Gem.bin_path("rubocop", "rubocop", version)
end
RUBOCOP_EOF

# Make executables executable
chmod +x "${GEM_BIN_DIR}/rspec"
chmod +x "${GEM_BIN_DIR}/rubocop"

echo "Ruby environment setup complete!"
echo "✅ Bundle installed"
echo "✅ RSpec available: $(bundle exec rspec --version | head -1)"
echo "✅ RuboCop available: $(bundle exec rubocop --version)"
