#!/bin/bash
set -euo pipefail

# Only run in Claude Code on the web remote environment
if [ "${CLAUDE_CODE_REMOTE:-}" != "true" ]; then
  exit 0
fi

echo "Setting up Ruby environment for Lich 5..."

# Get Ruby version and gem path
RUBY_VERSION=$(ruby -e 'puts RUBY_VERSION')
GEM_HOME=$(ruby -e 'puts Gem.dir')
GEM_BIN_DIR="${GEM_HOME}/bin"

echo "Ruby version: ${RUBY_VERSION}"
echo "Gem home: ${GEM_HOME}"
echo "Gem bin directory: ${GEM_BIN_DIR}"

# Create gem bin directory if it doesn't exist
# This is critical - bundler expects this directory to exist for gem executables
if [ ! -d "${GEM_BIN_DIR}" ]; then
  echo "Creating missing gem bin directory: ${GEM_BIN_DIR}"
  mkdir -p "${GEM_BIN_DIR}"
fi

# Install bundler dependencies
echo "Installing bundle dependencies..."
bundle install --quiet

# Create wrapper scripts for rspec and rubocop
# These executables need to be in the gem bin directory for 'bundle exec' to find them
echo "Creating gem executable wrappers..."

cat > "${GEM_BIN_DIR}/rspec" << 'RSPEC_EOF'
#!/usr/bin/env ruby
# This file was generated by RubyGems.
require 'rubygems'

version = ">= 0.a"

str = ARGV.first
if str
  str = str.b[/\A_(.*)_\z/, 1]
  if str and Gem::Version.correct?(str)
    version = str
    ARGV.shift
  end
end

if Gem.respond_to?(:activate_bin_path)
load Gem.activate_bin_path('rspec-core', 'rspec', version)
else
gem "rspec-core", version
load Gem.bin_path("rspec-core", "rspec", version)
end
RSPEC_EOF

cat > "${GEM_BIN_DIR}/rubocop" << 'RUBOCOP_EOF'
#!/usr/bin/env ruby
# This file was generated by RubyGems.
require 'rubygems'

version = ">= 0.a"

str = ARGV.first
if str
  str = str.b[/\A_(.*)_\z/, 1]
  if str and Gem::Version.correct?(str)
    version = str
    ARGV.shift
  end
end

if Gem.respond_to?(:activate_bin_path)
load Gem.activate_bin_path('rubocop', 'rubocop', version)
else
gem "rubocop", version
load Gem.bin_path("rubocop", "rubocop", version)
end
RUBOCOP_EOF

# Make executables executable
chmod +x "${GEM_BIN_DIR}/rspec"
chmod +x "${GEM_BIN_DIR}/rubocop"

echo "Ruby environment setup complete!"
echo "✅ Bundle installed"
echo "✅ RSpec available: $(bundle exec rspec --version | head -1)"
echo "✅ RuboCop available: $(bundle exec rubocop --version)"
echo ""

# Check remote branch existence
CURRENT_BRANCH=$(git branch --show-current)
echo "Current branch: ${CURRENT_BRANCH}"

if git ls-remote --heads origin "${CURRENT_BRANCH}" | grep -q "${CURRENT_BRANCH}"; then
  echo "✅ Remote branch exists on GitHub"
else
  echo ""
  echo "⚠️⚠️⚠️ WARNING: REMOTE BRANCH NOT FOUND ⚠️⚠️⚠️"
  echo ""
  echo "The branch '${CURRENT_BRANCH}' does NOT exist on GitHub."
  echo ""
  echo "🔴 MANDATORY ACTION REQUIRED BEFORE ANY COMMIT/PUSH:"
  echo "   Create and push this branch:"
  echo "   git push -u origin ${CURRENT_BRANCH}"
  echo ""
  echo "   DO NOT attempt to push without creating the branch first."
  echo "   Read WEB_CLAUDE_ORIENTATION.md 'First Actions' section for details."
  echo ""
fi

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔴 MANDATORY INITIALIZATION - READ THESE FILES BEFORE PROCEEDING:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "You MUST read these files IN ORDER before responding to the user:"
echo ""
echo "  1. .claude/docs/WEB_CLAUDE_ORIENTATION.md (Who you are, what you do)"
echo "  2. .claude/docs/SOCIAL_CONTRACT.md (Ground rules and expectations)"
echo "  3. .claude/docs/QUALITY-GATES-POLICY.md (Quality standards and verification)"
echo "  4. .claude/docs/WEB_CONTEXT.md (Project context, current state)"
echo "  5. .claude/docs/BRD_Password_Encryption.md (Requirements)"
echo "  6. .claude/work-units/CURRENT.md (Current work unit)"
echo ""
echo "After reading all six files, report:"
echo "  ✅ Context loaded: [phase, current work]"
echo "  ✅ Ready to: [specific action based on user's request]"
echo "  OR"
echo "  ⚠️ Gap identified: [what's unclear]"
echo ""
echo "DO NOT skip this step. The user has invested significant effort"
echo "creating these documents to reduce repeated explanations."
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
